site_name: Create React App
site_url: https://docs.fetch.ai/create-react-app
site_description: Everything you need to know about using our create-react-app template.
repo_url: https://github.com/fetchai/cra-template-cosmjs-keplr
site_author: developer@fetch.ai

theme:
  name: material
  logo: images/logo.png
  favicon: assets/images/favicon.ico
  feature:
    tabs: true
  custom_dir: custom_theme

nav:
  - Introduction: 'introduction.md'
  - Example DApp: 'example_dapp.md'

extra_css:
  - css/style.css

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
